#
# Copyright © 2022 Politecnico di Torino, Control and Computer Engineering Department, SMILIES group
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and 
# associated documentation files (the "Software"), to deal in the Software without restriction, 
# including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
# and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial 
# portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT 
# LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#######################################################################################
#
# LOAD REQUIRED PACKAGES
#
#######################################################################################

library(data.table)
library(dplyr)
library(tidyr)
library(ggplot2)

####### 

if (!(dir.exists("../output"))){
  dir.create("../output")
}
if (!(dir.exists("../output/PatchSeqDataset"))){
  dir.create("../output/PatchSeqDataset")
}
if (!(dir.exists("../output/PatchSeqDataset/IMAGES"))){
  dir.create("../output/PatchSeqDataset/IMAGES")
}

######
# Gene Ontology Enrichment plots

# Read files generated by ShinyGO output and generates plots

go_1 <- read.csv("../output/PatchSeqDataset/GO_enrichment_analysis/enrichment_molecular.csv")
go_2 <- read.csv("../output/PatchSeqDataset/GO_enrichment_analysis/enrichment_cellular.csv")
go_3 <- read.csv("../output/PatchSeqDataset/GO_enrichment_analysis/enrichment_biological.csv")

go_1 %>% arrange(Fold.Enrichment)  %>% mutate(Pathway = factor(Pathway, levels= Pathway)) %>%  dplyr::slice(-2, -1) %>% 
  ggplot(aes(x=Fold.Enrichment, y = Pathway, color= -log(Enrichment.FDR))) + 
  geom_segment(aes(xend=0, yend=Pathway), size = 1.5) + geom_point(aes(size=nGenes)) + 
  theme(axis.text = element_text(size = 45) ,title = element_text(size=45), panel.background = element_rect(fill = "white"), panel.grid.major = element_line(color = "grey80"), panel.grid.minor  = element_line(color = "grey90"),
        legend.text = element_text(size=40), legend.key.size = unit(30, "pt")) + 
  labs(color= "-log(FDR)" ,y="", x = "Fold Enrichment", title = "GO Molecular Function") 

ggsave(path = "../output/PatchSeqDataset/IMAGES", filename = "GO_molecular_plot.pdf", width = 2120, height = 1080, units= "px",scale = 3.5)


go_2 %>% arrange(Fold.Enrichment)  %>% mutate(Pathway = factor(Pathway, levels= Pathway)) %>%  dplyr::slice(-2, -1) %>% 
  ggplot(aes(x=Fold.Enrichment, y = Pathway, color= -log(Enrichment.FDR))) + 
  geom_segment(aes(xend=0, yend=Pathway), size = 1.5) + geom_point(aes(size=nGenes)) + 
  theme(axis.text = element_text(size = 45) ,title = element_text(size=45), panel.background = element_rect(fill = "white"), panel.grid.major = element_line(color = "grey80"), panel.grid.minor  = element_line(color = "grey90"),
        legend.text = element_text(size=40), legend.key.size = unit(30, "pt") ) +
  labs(color= "-log(FDR)" ,y="", x = "Fold Enrichment", title = "GO Cellular Component")

ggsave(path = "../output/PatchSeqDataset/IMAGES/", filename = "GO_cellular_plot.pdf", width = 2120, height = 1080, units= "px",scale = 3.5)



go_3 %>% arrange(Fold.Enrichment)  %>% mutate(Pathway = factor(Pathway, levels= Pathway)) %>%  dplyr::slice(-2, -1) %>% 
  ggplot(aes(x=Fold.Enrichment, y = Pathway, color= -log(Enrichment.FDR))) + 
  geom_segment(aes(xend=0, yend=Pathway), size = 1.5) + geom_point(aes(size=nGenes)) + 
  theme(axis.text = element_text(size = 45) ,title = element_text(size=45), panel.background = element_rect(fill = "white"), panel.grid.major = element_line(color = "grey80"), panel.grid.minor  = element_line(color = "grey90"),
        legend.text = element_text(size=40), legend.key.size = unit(30, "pt")) + 
  labs(color= "-log(FDR)" ,y="", x = "Fold Enrichment", title = "GO Biological Process")

ggsave(path = "../output/PatchSeqDataset/IMAGES/", filename = "GO_biological_plot.pdf", width = 2120, height = 1080, units= "px",scale = 3.5)

#####

